In [ ]:
import numpy as np #library to deal with multidimensional arrays
import random

#Create a numpy array of size 2 x 2 (2 rows and 2 columns)
arr = np.array([[1,2],[3,4]])
print(arr)

#Create a random numpy array of size 3 x 4
arr = np.random.rand(3,4)
print(f'\n{arr}')

#Create a numpy array of ones
arr = np.ones((4,2))
print(f'\n{arr}')

#Create a numpy array of zeroes
arr = np.zeros((3,4))
print(f'\n{arr}')

[[1 2]
 [3 4]]

[[0.1587723  0.07572258 0.3382869  0.92123122]
 [0.65665359 0.09897953 0.3838954  0.30281063]
 [0.05434382 0.01918071 0.328261   0.9644491 ]]

[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [15]:

# Create a random numpy array of size 6x3 and transpose it
arr = np.random.rand(6,3)
print(arr)

arr_transpose = arr.T
print('\n Transpose')
print(arr_transpose)

[[0.70116692 0.18332683 0.43800453]
 [0.77507974 0.17790151 0.81219912]
 [0.36860985 0.64987486 0.56177235]
 [0.10586312 0.33633398 0.19722241]
 [0.39198587 0.95128815 0.45577544]
 [0.59785382 0.31446817 0.5709237 ]]

 Transpose
[[0.70116692 0.77507974 0.36860985 0.10586312 0.39198587 0.59785382]
 [0.18332683 0.17790151 0.64987486 0.33633398 0.95128815 0.31446817]
 [0.43800453 0.81219912 0.56177235 0.19722241 0.45577544 0.5709237 ]]


In [19]:
# Create two random numpy array of size n x p and p x m
# and then compute the dot product


# Define the dimensions
# In this example, it is A = 3 x 4 matrix  and B = 4 x 2 matrix .
n = 3  # Number of rows for the first array
p = 4  # Number of columns for the first array and rows for the second array
m = 2  # Number of columns for the second array

# Create the random arrays
array1 = np.random.rand(n, p)
array2 = np.random.rand(p, m)

print(array1)
print(array2)

# Calculate the dot product

import numpy as np



dot_product = np.dot(array1, array2)
print(dot_product)

[[0.08553814 0.79574117 0.24106991 0.84177846]
 [0.67710774 0.49447866 0.29569283 0.67848876]
 [0.20485622 0.76852954 0.29860284 0.54395249]]
[[0.13588983 0.64104688]
 [0.56079044 0.82041616]
 [0.94299798 0.52074603]
 [0.26334379 0.73125712]]
[[0.90687337 1.44876557]
 [0.8268245  1.48986669]
 [0.88365028 1.31510187]]
